services:
  backend:
    build: .
    container_name: backend
    ports:
      - "3001:3000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - backend-network
    restart: unless-stopped
    volumes:
      - backend_uploads:/app/uploads

  postgres:
    image: postgres:16-alpine
    container_name: backend-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - backend_postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  redis:
    image: redis:7-alpine
    container_name: backend-redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:6380:6379"
    volumes:
      - backend_redis_data:/data
    networks:
      - backend-network

volumes:
  backend_postgres_data:
  backend_redis_data:
  backend_uploads:

networks:
  backend-network:
    driver: bridge
